### ISSUE TITLE
Formate of csv file

### ISSUE THREAD

**Issue by shahkushal** [cloudera/ades#2]
Hi, I have one doubt. What is the format(which all columns are there in that file) of input csv file, from which we are reading the data in ebgm.R?

**Comment by busbey** [comment]
The columns are defined in the [step 3 pig script](https://github.com/cloudera/ades/blob/master/src/main/pig/step3_generate_squashed_distribution.pig#L96)

````pig
/**
 * Finally, group the values by the actual count and the bin they were assigned
 * to, and compute the sum of the values and the total number of observations in
 * each bin to use as input to the external optimization routine.
 */
table_blocks = GROUP table_bins BY (actual, bin);
stats = FOREACH table_blocks GENERATE group.actual as actual, group.bin as bin,
    SUM(table_bins.value) as expected, COUNT(table_bins) as weight;
````

the rows from the stats generate call then get stored into the directory we do a getmerge on to form the CSV file.
